client_id = "1bfb615d6837e45ae34fb39a820c62ca"
name = "ShopDelta"
application_url = "https://shopdelta.vercel.app"
embedded = true
handle = "shopdelta"

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topic = "app/scopes_update"
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topic = "app/uninstalled"
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# keep only what you need; add read_all_orders only if justified in review
scopes = "read_orders,read_products"

[auth]
redirect_urls = ["https://shopdelta.vercel.app/auth/callback"]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = false
