# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f807ad274f7f2cd3f92f533cf7a75215"
name = "ShopDelta"
application_url = "https://shop-delta-1701-cs69-seven.vercel.app"
embedded = true
handle = "test-20425"

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_all_orders,write_products"

[auth]
redirect_urls = [
  "https://shop-delta-1701-cs69-seven.vercel.app/auth/callback",
  "https://shop-delta-1701-cs69-seven.vercel.app/auth/shopify/callback",
  "https://shop-delta-1701-cs69-seven.vercel.app/api/auth/callback"
]

[pos]
embedded = false

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = false
